### ISSUE TITLE
Example app uses old version of the bridge

### ISSUE THREAD

**Issue by shumailxyz** [sentiance/react-native-sentiance-example#14]
Thanks for the example app. 

The example app is on [`4.0.1`](https://github.com/sentiance/react-native-sentiance-example/blob/master/package.json#L13) however the current version is on `4.2.0`. 

Also, after updating to the newer version, I had to change RNSentiance in Podfile slightly for the app to compile:

```
pod 'SENTSDK', :podspec => '../node_modules/react-native-sentiance/ios/SENTSDK.podspec'
pod 'RNSentiance', :path => '../node_modules/react-native-sentiance/ios'
```

Perhaps you might want to update it.

**Comment by sebouh00** [comment]
@shumailxyz Thanks!

**Comment by countcain** [comment]
@shumailxyz thanks for reporting. We've updated it to use the latest bridge 4.3.1
With 4.3.1, you will need to remove SENTSDK from the Podfile. Please check https://github.com/sentiance/react-native-sentiance-example/blob/master/ios/Podfile#L37

**Comment by shumailxyz** [comment]
Thanks!
